### ISSUE TITLE
 IOS App crashing while adding device (objc)

### ISSUE THREAD

**Issue by gokselsina** [tuya/tuya-home-ios-sdk-sample-objc#12]
Hi. I cloned the repo named tuya-home-ios-sdk-sample-objc via github. I have completed all the installation steps correctly. But the app crashes. I press the Activator button and select the type of device to pair. For example, the temperature sensor. Then I do the device search and the device is detected. At this time, there is the device detected on the screen and the add button next to it. As soon as I press the add button, the application freezes and crashes. I have uploaded the image as a file attachment, you can review it. I did not make any development to the application. I'm installing bizbundle on the sdk you provided. The only information I can get about the problem is that during the crash I see "ID is invalid" in the logs. I don't know what ID she's talking about. Can you assist me on how to solve this problem?
![iScreen Shoter - 20230828100206119](https://github.com/tuya/tuya-home-ios-sdk-sample-objc/assets/115628199/d9d470d1-724d-4f06-b3e4-2756f1aa8b9b)

Video : https://www.youtube.com/watch?v=wQ5LV1nxVwY

**Comment by taojingGino** [comment]
1.Can you provide your mobile system version and Xcode version? This issue may be related to the version

2.Can you take a screenshot of all the information on the stack here？

<img width="189" alt="screen" src="https://github.com/tuya/tuya-home-ios-sdk-sample-objc/assets/59640671/f3a7a93e-15fb-4fb8-a5e0-e792c44e31ad">
@gokselsina

**Comment by gokselsina** [comment]
Hi,

xcode version : 14.3.1
ios version : 16.4

![image](https://github.com/tuya/tuya-home-ios-sdk-sample-objc/assets/115628199/2f936478-04cc-49a3-bb16-6bef0548b21c)

**Comment by gokselsina** [comment]
Hi, is there any solution for the issue?

**Comment by Proxy13** [comment]
Same.here.@taojingGino any solutions?

**Comment by taojingGino** [comment]
We did not reproduce this issue in the demo. Can you send your demo to the following email
taojing@tuya.com

@gokselsina @Proxy13

**Comment by gokselsina** [comment]
Hi,
Download link : https://drive.google.com/file/d/1XUpezuGKtAWgXn48MuVOw8Rd0O_Rcrkz/view?usp=sharing
@taojingGino

**Comment by gokselsina** [comment]
Did you get my email from goksel.sina@hotmail.com @taojingGino

**Comment by eyup356** [comment]
I think I'm having a similar problem, how can we proceed?

**Comment by tarikulker-js** [comment]
i have been following the issue for a long time. when will we find a solution? @taojingGino

**Comment by mustafaaygun** [comment]
ActivatorBizbundle ile cihaz eşlerken uygulama çöküyor yaz

**Comment by taojingGino** [comment]
@gokselsina 
We get the demo you send to me, but we still not crash
Can you provide all screen recordings and all logs of the app from startup to crash? thanks

and other guys, could you provide some information to help us investigate

**Comment by gokselsina** [comment]
Hi @taojingGino 
I recorded my experience
Video : https://www.youtube.com/watch?v=yv2Cjk9eCpY&t=9s
Logs : 
[tuya_bizbundle_sdk_logs.txt](https://github.com/tuya/tuya-home-ios-sdk-sample-objc/files/12585637/tuya_bizbundle_sdk_logs.txt)

**Comment by Proxy13** [comment]
@taojingGino same with attached video in previous comment .

**Comment by Proxy13** [comment]
It seems library level problem or xcode and iOS version related

**Comment by taojingGino** [comment]
We have determined that this issue will crash in the simulator，perform normally in iOS devices, and will be resolved in the upcoming 5.2.0 version sdk

**Comment by Proxy13** [comment]
thx for reply . we are trying real device(iPad 11 Pro M2)  right now. We got all permissions (networking-multicast and App ID Configuration ) .But device did not sent airkiss (multicast ) .we are trying to fix it. Do you have any idea about this problem ? we could sent all cert. settings also pls dont forget to test iPadOS

**Comment by Proxy13** [comment]
our cert 
https://developer.apple.com/contact/request/networking-multicast

Access Wi-Fi Information
Custom Network Protocol
DriverKit (development)
DriverKit Allow Third Party UserClients
DriverKit Family Networking (development)
Extended Virtual Addressing
HomeKit
Hotspot
Network Extensions

**Comment by Proxy13** [comment]
@taojingGino

**Comment by taojingGino** [comment]
This issue may be related to the compatibility of the router

You can try setting up a router, turn off 5GHz Wi Fi, only keep 2.4GHz Wi Fi, restart the router, restart the phone, and then try network distribution again

@Proxy13

**Comment by Proxy13** [comment]
@taojingGino  also we can connect devices using tuya demo application in applestore same network and router

**Comment by taojingGino** [comment]
did you add
<dict> 
<key>com.apple.developer.networking.multicast</key>
</dict>
 in your xxx.entitlements
 @Proxy13

**Comment by gokselsina** [comment]
solved like this @taojingGino  
new version is expected. Thank you for your support 🙏🏻

**Comment by mustafaaygun** [comment]
Ooh nice job @gokselsina.
