### ISSUE TITLE
XCode 15 give this error like duplicate symbol

### ISSUE THREAD

**Issue by amacymind** [tuya/tuya-home-ios-sdk-sample-objc#13]
Hello,
Hello team,
As in Xcode 15 when add TuyaSmartHomeKit sdk in my proejct its gives error like, duplicate symbols.
I also attached screenshot for that. I used pod "TuyaSmartHomeKit" for install tuya sdk.
![Screenshot 2023-09-25 at 4 22 09 PM](https://github.com/tuya/tuya-home-ios-sdk-sample-objc/assets/7520475/e65a425f-5dfc-4379-b7fe-191888b57713)

Thanks,

**Comment by taojingGino** [comment]
We have fixed this issue in the latest 4.0 and 5.0 versions. If you still encounter this error after upgrading to the latest version, please provide the Podfile and Podfile.lock files

@amacymind

**Comment by amacymind** [comment]
Here's my pod files.
[podfile.zip](https://github.com/tuya/tuya-home-ios-sdk-sample-objc/files/12725614/podfile.zip)
@taojingGino

**Comment by taojingGino** [comment]
pod "TuyaSmartHomeKit", "~> 5.0.0"

Write it like this to fix the version
@amacymind

**Comment by taojingGino** [comment]
source 'https://github.com/tuya/tuya-pod-specs.git'

and you need and this
@amacymind

**Comment by amacymind** [comment]
Its gives error like, CocoaPods could not find compatible versions for pod "TuyaSmartHomeKit":
  In Podfile:
    TuyaSmartHomeKit (~> 5.0.0)
![Screenshot 2023-09-26 at 4 20 41 PM](https://github.com/tuya/tuya-home-ios-sdk-sample-objc/assets/7520475/862f01ab-8b10-47e7-b706-aac96fd63ecb)
 @taojingGino

**Comment by taojingGino** [comment]
it's ThingSmartHomeKit 
@amacymind
