### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by Md-Mahfuzur-Rahman** [tuya/tuya-home-ios-sdk-sample-objc#14]
Hi all, I am facing an issue. here it is ,

Undefined symbol: _read_keys_from_content
Undefined symbol: _read_keys_from_file
Undefined symbol: _thingctypt_CString
Undefined symbol: _thingctypt_OCString

My environment:
XCode - 14.2
Mac - intel , Monterey

=====     Inside POD   ============
source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/tuya/TuyaPublicSpecs.git'
source 'https://github.com/tuya/tuya-pod-specs.git'

target 'TuyaAppSDKSample-iOS-ObjC' do

  pod 'ThingSmartHomeKit', '~> 5.0.0'
  pod 'ThingSmartCryption', :path => './'
end

post_install do |installer|
  `cd TuyaAppSDKSample-iOS-ObjC; [[ -f AppKey.h ]] || cp AppKey.h.default AppKey.h;`
end

=============

Could you please help ?

![Screenshot 2023-10-06 at 10 45 20 AM](https://github.com/tuya/tuya-home-ios-sdk-sample-objc/assets/35328874/b817c11d-51d9-41d3-96dd-c3bf292fc024)

**Comment by taojingGino** [comment]
https://developer.tuya.com/cn/docs/app-development/integrate-sdk?id=Ka5d52ewngdoi#title-3-%E4%BD%BF%E7%94%A8%20CocoaPods%20%E9%9B%86%E6%88%90

please check this docment,this error looks like you miss ThingSmartCryption's "build" files
@Md-Mahfuzur-Rahman

**Comment by Md-Mahfuzur-Rahman** [comment]
Thank you @taojingGino, for your prompt reply. It was a great help. I have solved the issue.
