### ISSUE TITLE
Unable to find Bluetooth Device

### ISSUE THREAD

**Issue by LiliaRud** [tuya/tuya-home-ios-sdk-sample-objc#15]
Hi! I'm developing an app using SDK to control Ambiance Light device. I've cloned this example and wasn't able to find my device through Bluetooth. While with Smart Life app I can find, connect and control it.

Seems like **didDiscoveryDeviceWithDeviceInfo** doesn't call at all.

I'm adding screen records from both this app and Smart Life app, also adding logs.

**My env:**
iPhone 13 Pro
iOS 17.1.2
Xcode 15.2

**Logs:**

```
startAuto listening
This application is for testing only, but not for commercial use. If the number of registered users reaches the limit, new users cannot be registered.
[blekit] -- start scan Scantype:1 cacheStatu:1
ThingBLEScan  ==> BLE Device Start Listening  : discoverServiceUUID 
 service (
) 
 options {
}
[blekit] start connect system (null) <__NSMallocBlock__: 0x281d23090>
This application is for testing only, but not for commercial use. If the number of registered users reaches the limit, new users cannot be registered.
This application is for testing only, but not for commercial use. If the number of registered users reaches the limit, new users cannot be registered.
Connection 6: cleaning up
Connection 6: done
This application is for testing only, but not for commercial use. If the number of registered users reaches the limit, new users cannot be registered.
ble stop scan clearCache:1
```

https://github.com/tuya/tuya-home-ios-sdk-sample-objc/assets/17880913/c709bb3c-f3b5-4ccc-aa25-0d60bbbb289e

https://github.com/tuya/tuya-home-ios-sdk-sample-objc/assets/17880913/27458c5f-6e33-4422-b82e-2dd0c6649bf6

**All permissions are granted to app:**
![Screenshot 2024-01-11 at 00 20 16 jpeg](https://github.com/tuya/tuya-home-ios-sdk-sample-objc/assets/17880913/9a775ebe-7199-4608-bfb1-89ab4b0daaeb)

Thank you for any help!

**Comment by taojingGino** [comment]
@LiliaRud pls check this doc，if you add this permission？and Capabilities Access Wi-Fi Information
https://developer.tuya.com/en/docs/app-development/ble?id=Ka5vcxzbglphd#title-1-Permissions

**Comment by LiliaRud** [comment]
@taojingGino yes, all permissions and Capabilities Access Wi-Fi Information are added

**Comment by LiliaRud** [comment]
Ok, so I added another permission (which wasn't mentioned in any documentation) and it fixed warnings mentioned above, but it still can't find the device and doesn't trigger **didDiscoveryDeviceWithDeviceInfo**

```
<key>UIBackgroundModes</key>
<array>
	<string>bluetooth-central</string>
</array>
```

Logs now are:
[```
blekit] -- start scan Scantype:1 cacheStatu:1
ThingBLEScan  ==> BLE Device Start Listening  : discoverServiceUUID 
 service (
    A201,
    FD50
) 
 options {
    kCBScanOptionAllowDuplicates = 0;
}
CBCentralManagerStatePoweredOn
ThingBLEScan  ==> BLE Device Start Listening  : discoverServiceUUID 
 service (
    A201,
    FD50
) 
 options {
    kCBScanOptionAllowDuplicates = 0;
}
[blekit] start connect system (null) <__NSMallocBlock__: 0x280dd2460>
This application is for testing only, but not for commercial use. If the number of registered users reaches the limit, new users cannot be registered.
This application is for testing only, but not for commercial use. If the number of registered users reaches the limit, new users cannot be registered.
This application is for testing only, but not for commercial use. If the number of registered users reaches the limit, new users cannot be registered.
Connection 1: cleaning up
Connection 3: cleaning up
Connection 1: done
Connection 3: done
ble stop scan clearCache:1

```

**Comment by taojingGino** [comment]
pls check this permission
<img width="861" alt="111" src="https://github.com/tuya/tuya-home-ios-sdk-sample-objc/assets/59640671/0cccfacd-c033-49d1-a312-e5457532f45c">

Unable to scan Bluetooth devices, it is highly likely that these two permissions were not added
@LiliaRud

**Comment by LiliaRud** [comment]
@taojingGino all permissions are set
       ```
         <key>NSBluetoothAlwaysUsageDescription</key>
	<string>For Bluetooth scan</string>
	<key>NSBluetoothPeripheralUsageDescription</key>
	<string>For Bluetooth scan</string>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>For Bluetooth scan</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>For Bluetooth scan</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>For Bluetooth scan</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>bluetooth-central</string>
	</array>
```

**Comment by taojingGino** [comment]
Everything that needs to be added looks have been added, Can you try another Bluetooth device for testing? We have run our official demo here and can find Bluetooth devices
@LiliaRud

**Comment by LiliaRud** [comment]
@taojingGino as it turned out, I was provided with wrong information and device is Bluetooth Mesh as I figured out by myself.
But when I was trying different connection methods from this app, I wasn't able to test SIG Mesh scan as there wasn't implemented **createSIGMeshWithHomeId** method, so I added it and then was able to find the device.
